### ISSUE TITLE
page is not loading

### ISSUE THREAD

**Issue by adnanjpg** [code-a-man/calisma-mekanlari-app#4]
page state stays empty, dropdown state stays at "Şehirler Yükleniyor"
<img width="1351" alt="Screenshot 2024-04-25 at 12 53 09 AM" src="https://github.com/code-a-man/calisma-mekanlari-app/assets/54329101/e4056a28-2b2c-4007-b3d8-959e062786be">

this issue probably originates from how the data is processed
<img width="808" alt="Screenshot 2024-04-25 at 12 53 43 AM" src="https://github.com/code-a-man/calisma-mekanlari-app/assets/54329101/4c921dda-97c6-420f-98bc-1307cc5bf9cb">
```
596-00ebd46acf1b8d25.js:1 Error fetching data: TypeError: Cannot read properties of undefined (reading 'replace')
    at n (page-eda4ebbf5c4181a4.js:1:250)
    at page-eda4ebbf5c4181a4.js:1:883
    at Array.map (<anonymous>)
    at i (page-eda4ebbf5c4181a4.js:1:616)
window.console.error @ 596-00ebd46acf1b8d25.js:1
```

**Comment by code-a-man** [comment]
Thank you for heads-up :heart: I believe the site is malfunctioning due to disruption in table layout. I will address this either later today or within this week.

**Comment by ramazansancar** [comment]
[fix: Data provider updated. #5](https://github.com/code-a-man/calisma-mekanlari-app/pull/5) I solved the problem with this PR. It was only a problem with the data coming empty in the Prod environment. In addition, since the main repo was not up to date, I reviewed the other repos and updated them to the latest.

@code-a-man @adnanjpg
